using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace Zeus.UI.Events
{
    /// <summary>
    /// Provides infortmation about a <see cref="Controls.ZeusClock.SelectedTimeChanged"/> event.
    /// </summary>
    public class ZeusSelectedTimeChangedEventArgs : RoutedEventArgs
    {
        #region Constructor

        /// <summary>
        /// Initialize a new instance of <see cref="ZeusSelectedTimeChangedEventArgs"/>.
        /// </summary>
        /// <param name="eventId">The <see cref="RoutedEvent"/> associated with the event.</param>
        /// <param name="oldValue">The old property value.</param>
        /// <param name="newValue">The new property value.</param>
        /// <param name="fromIncreaeButton">A flag that indicates if the valued has been changed using the increase buttons.</param>
        public ZeusSelectedTimeChangedEventArgs(RoutedEvent eventId, TimeSpan? oldValue, TimeSpan? newValue, bool fromIncreaeButton) : base(eventId)
        {
            OldValue = oldValue;
            NewValue = newValue;
            FromIncreaseButton = fromIncreaeButton;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets the old property value.
        /// </summary>
        public TimeSpan? OldValue { get; private set; }
        /// <summary>
        /// Gets the new property value.
        /// </summary>
        public TimeSpan? NewValue { get; private set; }
        /// <summary>
        /// Gets a flag that indicates if the event has been generated by the increase buttons.
        /// </summary>
        public bool FromIncreaseButton { get; private set; }

        #endregion
    }
}
